[workspace]
members = [
  "general/echo/kmdf/driver/*",
  "general/echo/kmdf/exe",
  "tools/dv/kmdf/fail_driver_pool_leak",
]
resolver = "2"

[workspace.package]
edition = "2021"
publish = false
repository = "https://github.com/microsoft/windows-rust-driver-samples"
license = "MIT OR Apache-2.0"

[workspace.metadata.wdk.driver-model]
driver-type = "KMDF"
kmdf-version-major = 1
target-kmdf-version-minor = 33

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true

[workspace.dependencies]
anyhow = "1.0.89"
paste = "1.0.14"
wdk = { git = "https://github.com/microsoft/windows-drivers-rs.git", rev = "4992b46392d3c8af1967832c6bb6f280227f561b" }
wdk-alloc = { git = "https://github.com/microsoft/windows-drivers-rs.git", rev = "4992b46392d3c8af1967832c6bb6f280227f561b" }
wdk-build = { git = "https://github.com/microsoft/windows-drivers-rs.git", rev = "4992b46392d3c8af1967832c6bb6f280227f561b" }
wdk-panic = { git = "https://github.com/microsoft/windows-drivers-rs.git", rev = "4992b46392d3c8af1967832c6bb6f280227f561b" }
wdk-sys = { git = "https://github.com/microsoft/windows-drivers-rs.git", rev = "4992b46392d3c8af1967832c6bb6f280227f561b" }
